routes/admin.php
<?php

use App\Http\Controllers\Admin\CacheV1Controller;
use App\Http\Controllers\Admin\TokenPriceV1Controller;
use App\Http\Controllers\Admin\UserV1Controller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminV1Controller;
use App\Http\Controllers\Admin\PayableV1Controller;
use App\Http\Controllers\Admin\SettingsV1Controller;
use App\Http\Controllers\Admin\TransactionV1Controller;

Route::group(['prefix' => 'admin', 'middleware' => ['role:Admin|Moderator']], function() {
    Route::get('/', [AdminV1Controller::class, 'index'])->name('admin.dashboard');
    Route::get('/users', [UserV1Controller::class, 'index'])->name('admin.users.index');
    Route::get('/users/{user}', [UserV1Controller::class, 'show'])->name('admin.users.show');
    Route::get('/users/{user}/edit', [UserV1Controller::class, 'edit'])->name('admin.users.edit');
    Route::put('/users/{user}', [UserV1Controller::class, 'update'])->name('admin.users.update');
    Route::get('/users/{user}/transactions', [UserV1Controller::class, 'transactions'])->name('admin.users.transactions');

    Route::get('/transactions', [TransactionV1Controller::class, 'index'])->name('admin.transaction.index');
    // Settings
    Route::group(['prefix' => 'settings'], function () {
        Route::resource('/payable-tokens', PayableV1Controller::class);
        Route::get('/site-settings', [SettingsV1Controller::class, 'index'])->name('admin.settings');
        Route::put('/site-settings', [SettingsV1Controller::class, 'update'])->name('admin.settings.update');
        Route::get('/token-price', [TokenPriceV1Controller::class, 'index'])->name('admin.token-price.index');
        Route::put('/token-price', [TokenPriceV1Controller::class, 'update'])->name('admin.token-price.update');
        Route::get('/cache-clear', [CacheV1Controller::class, 'index'])->name('admin.cache.index');
        Route::post('/cache-clear', [CacheV1Controller::class, 'clearCache'])->name('admin.cache.clear');
    });
});

routes/web.php
<?php

use App\Http\Controllers\AppController;
use App\Http\Controllers\TransactionV1Controller;
use App\Http\Controllers\TwoFactorAuthV1Controller;
use Illuminate\Support\Facades\Route;

Route::get('/', [AppController::class, 'index'])->name('index');

Route::middleware(['auth', '2fa'])->group(function () {
    /**
     * Profile routes.
     */
    require __DIR__.'/profile.php';

    /**
     * Admin Routes.
     */
    require __DIR__.'/admin.php';

    /**
     * Investor & Verified user routes.
     */
    require __DIR__.'/investor.php';

    Route::post('/api/transaction', [TransactionV1Controller::class, 'store'])->name('transaction.store');
    Route::post('/api/referral-transaction', [TransactionV1Controller::class, 'referralTransaction'])->name('referral-transaction');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/two-factor-auth', [TwoFactorAuthV1Controller::class, 'index'])->name('two-factor-auth');
    Route::post('/two-factor-auth', [TwoFactorAuthV1Controller::class, 'store'])->name('two-factor-auth.store');
});

require __DIR__.'/auth.php';

app/Models/PayableToken.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PayableToken extends Model
{
    use HasFactory;

    protected $guarded = [];

    // active scope
    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/payable-tokens/create.blade.php
@section('title')
    Create Payable Token
@endsection
<x-app-layout>
    <x-card title="Add new payable token">
        <x-validation-errors class="pb-6 mb-6 border-b" :errors="$errors" />

        @include('admin.payable-tokens.form', [
            'type' => 'create',
            'item' => null,
        ])
    </x-card>
</x-app-layout>

resources/views/admin/payable-tokens/edit.blade.php
@section('title')
    Edit {{ $payableToken->name }} Token
@endsection
<x-app-layout>
    <x-card title="Edit {{ $payableToken->name }} Token">
        <x-validation-errors class="pb-6 mb-6 border-b" :errors="$errors" />

        @include('admin.payable-tokens.form', [
            'type' => 'edit',
            'item' => $payableToken,
        ])
    </x-card>
</x-app-layout>

resources/views/admin/payable-tokens/form.blade.php
 @php
     $isEdit = $type == 'edit';
 @endphp
 <form x-data action="{{ $isEdit ? route('payable-tokens.update', $item) : route('payable-tokens.store') }}"
     @submit.prevent="{{ $isEdit ? 'e => e.target.submit()' : '$store.wallet.addNewToken($event)' }}" method="POST"
     enctype="multipart/form-data">
     @csrf

     @if ($isEdit)
         @method('PUT')
     @else
         <div class="mb-6">
             <x-wallet-connect-button />
         </div>
     @endif

     <x-loader x-show="$store.wallet.loading" />

     <div class="grid grid-cols-1 gap-4 lg:grid-cols-3">
         <div class="col-span-3">
             <x-input-field name="contract_address" type="text" required value="{{ $item?->contract_address }}"
                 pattern="^0x[a-fA-F0-9]{40}$" :disabled="$isEdit"
                 description="Contract address must start with 0x and have 42 chars" />
         </div>
         <x-input-field name="symbol" type="text" required value="{{ $item?->symbol }}" pattern="^[a-zA-Z0-9]{1,5}$"
             description="Symbol must not be more than 5 chars" />
         <x-input-field name="name" type="text" required value="{{ $item?->name }}" />
         <x-input-field name="decimals" type="number" :disabled="$isEdit" value="{{ $item?->decimals }}" />
         <label for="status" class="relative inline-flex items-center mt-2 cursor-pointer">
             <input type="checkbox" @checked(old('status') ?? ($item?->status ?? true)) id="status" name="status" class="sr-only peer">
             <div
                 class="w-11 h-6 bg-gray-200 rounded-full peer peer-focus:ring-4 peer-focus:ring-primary-300 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-600">
             </div>
             <span class="ml-3 text-sm font-medium text-gray-900 dark:text-white">Active Token</span>
         </label>
         <div class="col-span-3 py-4 rounded-lg" role="tabpanel">
             <p class="mb-4 text-lg font-semibold text-primary-700">
                 Upload Token Image
             </p>
             <x-dropzone class="max-w-xl mb-4" name="image" accept="image/*" :required="!$isEdit" />
         </div>
     </div>

     <div class="flex items-center gap-2 mb-6">
         <button class="btn btn-primary" type="submit">
             Submit
         </button>
         <a href="{{ route('payable-tokens.index') }}" class="btn btn-secondary-alt">
             Back
         </a>
     </div>
 </form>

resources/views/admin/payable-tokens/index.blade.php
@section('title')
    Show All Payable Tokens
@endsection
<x-app-layout>
    <x-card title="Payable Tokens List">
        @php
            $headers = ['#', 'Token', 'Decimals', 'Contract Address', 'Status', 'Action'];
        @endphp

        <div class="flex justify-end mb-6">
            <a href="{{ route('payable-tokens.create') }}" class="capitalize btn btn-primary">Add new payable token</a>
        </div>

        <x-session-status class="mb-6" />

        <x-table class="min-h-[calc(100vh-320px)]" :headers="$headers">
            @forelse ($tokens as $item)
                <tr
                    class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                    <td class="px-6 py-4">
                        {{ $loop->iteration }}
                    </td>
                    <td class="px-6 py-4">
                        <div class="flex items-center gap-3">
                            <img src="{{ Storage::url($item->image) }}" class="h-10 max-w-full"
                                alt="{{ $item->symbol }}">
                            <div class="flex flex-col">
                                <span class="mb-1 font-semibold">{{ $item->symbol }}</span>
                                <span class="text-gray-500 dark:text-gray-200">{{ $item->name }}</span>
                            </div>
                        </div>
                    </td>
                    <td class="px-6 py-4">
                        {{ $item->decimals }}
                    </td>
                    <td class="px-6 py-4">
                        {{ $item->contract_address }}
                    </td>
                    <td class="px-6 py-4">
                        @if ($item->status)
                            <x-badge type="success">Active</x-badge>
                        @else
                            <x-badge type="danger">Inactive</x-badge>
                        @endif
                    </td>
                    <td class="px-6 py-4">
                        <x-dropdown width="48">
                            <x-slot:trigger>
                                <button class="btn btn-sm btn-secondary-alt" type="button">
                                    <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z">
                                        </path>
                                    </svg>
                                </button>
                            </x-slot:trigger>

                            <x-slot:content>
                                <x-dropdown-link href="{{ route('payable-tokens.edit', $item) }}"> Edit
                                </x-dropdown-link>
                                <hr class="border-gray-100 dark:border-gray-600" />
                                <form action="{{ route('payable-tokens.destroy', $item) }}" method="POST">
                                    @csrf
                                    <input type="hidden" name="_method" value="DELETE">
                                    <x-dropdown-link href="#"
                                        onclick="confirmModal({text: 'Want to delete ({{ $item->symbol }}) token?'}, () => this.closest('form').submit())">
                                        Delete
                                    </x-dropdown-link>
                                </form>
                            </x-slot:content>
                        </x-dropdown>
                    </td>
                </tr>
            @empty
                <tr>
                    <th colspan="{{ count($headers) }}"
                        class="w-full p-6 text-lg font-semibold text-center text-gray-500 dark:text-gray-200">
                        There's no tokens yet. <a href="{{ route('payable-tokens.create') }}" class="text-blue-500">Add
                            new token</a>
                    </th>
                </tr>
            @endforelse

            <x-slot:pagination>
                {{ $tokens->links() }}
            </x-slot:pagination>
        </x-table>
    </x-card>
</x-app-layout>